### ISSUE TITLE
[BUG] - java.lang.RuntimeException: Unable to pause activity

### ISSUE THREAD

**Issue by Pentaphon** [damontecres/Wholphin#200]
### Description

This popped up when I re-opened the app after not using it for an hour or so. Log below.

### Reproduction steps

1. Nothing to report other than this crash happened when I opened the app. 

### App Version

0.2.8-51-g96c856e (mpv)

### Server Version

10.11.2

### Device

Onn 4K Plus

### Logs

[upload_Wholphin_0.2.8-51-g96c856e_20251112022227_7c42a99ef2564473991fd54f5c2e8422.log](https://github.com/user-attachments/files/23490723/upload_Wholphin_0.2.8-51-g96c856e_20251112022227_7c42a99ef2564473991fd54f5c2e8422.log)

**Comment by damontecres** [comment]
Fixed by 9b60c00, but it'll take a few minutes to build and publish

**Comment by Pentaphon** [comment]
@damontecres updated and unfortunately it is still crashing the same way. I even did a restart of the entire OS just to be sure. 

[upload_Wholphin_0.2.8-52-g9b60c00_20251112080741_aae1ba3fe6f84f0994f95bb8aa620439.log](https://github.com/user-attachments/files/23494873/upload_Wholphin_0.2.8-52-g9b60c00_20251112080741_aae1ba3fe6f84f0994f95bb8aa620439.log)

**Comment by damontecres** [comment]
Sorry @Pentaphon! 734d5ca should definitely fix it. I was being overly aggressive in checks about whether `libmpv` was loaded or not. But for many situations, such as backgrounding the app, it doesn't matter.
